import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import devbrandon from "../public/dev-brandon.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import brandonlogo from "../public/logo2.png"
import {useState} from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Brandon's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-gray-200 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 flex justify-between">
            <Image src={brandonlogo} width={350} height={350} className="-m-5" />
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-blue-400 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1vVDFW8Amj6eg1LDVXHx4uIGLU02aGQRC/view"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mb-6 -mt-12 overflow-hidden md:h-96 md:w-96">
            <Image src={devbrandon} layout="fill" objectFit="cover" alt="icwwons" />
          </div>
            <h2 className="font-JoseBold text-5xl py-2 text-blue-500 font-medium md:text-7xl">
              Brandon Sandoval
            </h2>
            <h3 className="font-JoseRegular text-2xl py-2 md:text-4xl">
              Full Stack Software Engineer.
            </h3>
            <p className=" font-JoseLight text-xl py-5 leading-8 text-black md:text-2xl max-w-xl mx-auto">
            First generation bilingual junior full stack engineer with experience in HTML, CSS, JavaScript, React, and Node.js. I have an understanding of both front-end and back-end development, and I am comfortable working with a wide range of tools and technologies to create cohesive, high-performance software solutions.

            </p>
          </div>
          <div className="text-6xl flex justify-center gap-16 py-3 -mt-10 mb-10 text-gray-600">
            <a className="hover:text-blue-500 duration-300 ease-in-out" href="https://twitter.com/mkdirbrandon">
            <AiFillTwitterCircle />
            </a>
            <a className="hover:text-blue-500 duration-300 ease-in-out" href="https://www.linkedin.com/in/brandon-s-877148a8/">
            <AiFillLinkedin />
            </a>
            <a className="hover:text-blue-500 duration-300 ease-in-out" href="https://github.com/brand310">
            <AiFillGithub />
            </a>
          </div>
        </section>


        <section>
          <div>
            <h3 className=" font-JoseRegular text-3xl py-1">About Me</h3>
            <p className=" font-JoseRegular text-md py-2 leading-8 text-gray-800">
              I am particularly skilled in using <span className=" text-blue-600 font-JoseBold">React</span> to build responsive, dynamic user interfaces, and I am well-versed in the latest trends and best practices in front-end development. I also have experience with using <span className="text-blue-600 font-JoseBold">Node.js</span> to build server-side applications, and I am comfortable using tools like Express.js and MongoDB to build server-side applications.

            </p>
            <p className=" font-JoseRegular text-md py-2 leading-8 text-gray-800">
            I am a strong collaborator and communicator, and I enjoy working with teams to create solutions. Whether I am working on a small personal project or contributing to a larger team effort. I have always loved talking to people and giving full presentation on projects that I can be proud of. I love learning and I’m always seeking out new opportunities to expand my skills and knowledge, whether that means learning a new programming language or mastering a new tool or framework.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
                alt="icons"
              />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={consulting}
                width={100}
                height={100}
                alt="icons"
              />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={code}
                width={100}
                height={100}
                alt="icons"
              />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

      
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
    </>
  );
}
